name: tfdoc
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tfdoc:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Generate TF Docs
        uses: terraform-docs/gh-actions@v0
        with:
          working-dir: .
          output-file: README.md
          git-push: true
          git-commit-message: "fix: terraform-docs"