---
name: tfsec
on: [push, pull_request]

jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init --backend=false
      - name: tfsec
        uses: reviewdog/action-tfsec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}